name: Refresh notes

on:
  workflow_dispatch:
  schedule:
    - cron:  '27 5 * * *'

env:
  LANG: "nl_BE.UTF-8"

jobs:
  refreshscript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Call the BEnotes_without_hashtag.sh script
      run: bash BEnotes_without_hashtag.sh

    - name: Push to remote
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "none@empty.com"
        git add data
        git add html
        git commit -m "Update geojson files (actions)"
        git push
